import "./globals.css";
import { AuthProvider } from "./sessionProviders";
import { GeistSans } from "geist/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className={"bg-zinc-50"}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
