import "./globals.css";
import { AuthProvider } from "./sessionProviders";
import { GeistSans } from "geist/font";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Lettre",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={"bg-zinc-50"}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
